ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: opera
    version: latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: 7.0..latest
  - name: android
    version: 4.0..latest