ui: mocha-bdd
browsers:
  - name: chrome
    version: 40..latest
  - name: firefox
    version: 35..latest
  - name: safari
    version: 7..latest
  - name: ie
    version: 10..latest
  - name: iphone
    version: 7.0..latest
  - name: android
    version: 4.1..latest